#!/usr/bin/env bash
set -euo pipefail
out(){ printf "\033[1;32m%s\033[0m\n" "$1"; sleep 0.35; }
out '$ prime-agent'
out 'Track this session with a Jira story or ticket? [y/N] y'
out 'Tracking enabled.'
out '$ /jira-time doctor'
out 'Atlassian MCP is configured. Jira tools available.'
out '$ /jira-time start DEMO-123'
out 'Tracking DEMO-123.'
out '$ /jira-time status'
out 'active; issue=DEMO-123; 25m active'
out '$ /timing today'
out '2026-08-16 work interpretation'
out ' testing: 12.0m (4 events)'
out ' debugging: 8.0m (2 events)'
out '$ /jira-time report'
out 'Adapter report'
out 'Prime Agent timing: 20m across 1 session'
out 'Jira time ledger: 25m across 1 entry'
out 'Pending Jira entries: 0'
out '$ /jira-time stop'
out 'Proposed Jira worklog: DEMO-123, 25 minutes'
out 'Submit to Jira? [y/N] y'
out 'Confirmed. Worklog submitted through Atlassian MCP.'
